name: Daily Forecast Update

on:
  schedule:
    - cron: "0 0 * * *"  # every day at 00:00 UTC
  workflow_dispatch:      # lets you manually run it

jobs:
  run-forecast:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v4

      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      
      - name: Install dependencies
        run: pip install -r requirements.txt

      
      - name: Run forecast and actual update script
        run: |
          python scripts/pull_forecast.py
          python scripts/pull_actual.py

      # 5. Commit updated CSV back to repo
      - name: Commit changes
        run: |
          git config --global user.name "alexanderjefferson"
          git config --global user.email "github-actions@github.com"
          git add data/forecasts/forecasts_master.csv
          git add data/observations/daily_actual.csv
          git commit -m "daily forecast update" || echo "No changes to commit"
          git push
